defaults: &defaults
  adapter: mysql2
  username: root
  password:
  database: ninja_corgi_<%= Rails.env %>
  pool: 5
  timeout: 5000
  host: localhost

development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
